MODULE.name = "Tying"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds Tying Items That Serve As Handcuffs. Enchance Roleplay Overall."
