--- Configuration for Alcoholism Module.
-- @configuration Alcoholism
--- This table defines the default settings for the Alcoholism Module.
-- @realm shared
-- @table Configuration
-- @field TickTime Specifies the tick time in seconds for alcohol effects | **number**
-- @field DegradeRate Specifies the rate at which alcohol effects degrade over time | **number**
-- @field AddAlpha Specifies the alpha value added to the screen for alcohol effects | **number**
-- @field EffectDelay Specifies the delay in seconds before alcohol effects are applied | **number**
-- @field DrunkNotifyThreshold Specifies the threshold value for notifying players of drunkenness | **number**
