--- Configuration for Advert Module.
-- @configuration Advert
--- This table defines the default settings for the Advert Module.
-- @realm shared
-- @table Configuration
-- @field AdvertPrice The price for making an advertisement | **integer**
-- @field AdvertCooldown The cooldown time in seconds before a user can make another advertisement | **integer**
